#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Send branding to container stdout.
cat /etc/s6-overlay/s6-rc.d/init-branding/branding

# Send build info to container stdout if it exists.
if [ -e /build_info ]; then
    cat /build_info
fi
