#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Set UID and GID from container environment variables or fallback to defaults.
PUID=${PUID:-911}
PGID=${PUID:-911}

# Modify the abc user ID and group ID.
groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

# Send the branding to stdout.
cat /etc/s6-overlay/s6-rc.d/init-adduser/branding

# Send the container version and build date to stdout.
cat /build_info

# Send the final abc user ID and group ID to stdout.
echo "
-------------------------------------------
GID/UID
-------------------------------------------
User UID:    $(id -u abc)
User GID:    $(id -g abc)
-------------------------------------------
"

# Fix ownership on the base image root directories.
chown abc:abc -R /app
chown abc:abc -R /config
chown abc:abc -R /defaults